/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataMahasiswaUAS;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.io.InputStreamReader;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.HashMap;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author LENOVO
 */
public class NadifJframe extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;

    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/DataMahasiswaUAS";
    String user = "postgres";
    String password = "12345678";
    private Object txtId;
    private javax.swing.JButton btnRefresh;

    public NadifJframe() {
        initComponents();
        koneksi();
        tampil();
    }
    public void koneksi() {
        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);
            System.out.println("Koneksi berhasil!");
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Koneksi gagal!");
        }
    }
    private void tampil() {
         EntityManager em = Persistence.createEntityManagerFactory("MataKuliah3PU").createEntityManager();
        
        try {
            Query query = em.createNamedQuery("Mahasiswa.findAll");
            List<Mahasiswa> resultList = query.getResultList();
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); 
            
            for (Mahasiswa m : resultList) {
                Object[] baris = new Object[5];
                baris[0] = m.getNIM();
                baris[1] = m.getNama();
                baris[2] = m.getAlamat();
                baris[3] = m.getAsalSma();
                baris[4] = m.getNamaOrtu();
                model.addRow(baris);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            em.close();
        }
    }
     public void clear() {
        tfNIM.setText("");
        tfNama.setText("");
        tfAlamat.setText("");
        tfAsal.setText("");
        tfNamaOrtu.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNIM = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfAlamat = new javax.swing.JTextField();
        tfAsal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnUpdate = new java.awt.Button();
        btnTambah = new java.awt.Button();
        btnDelete = new java.awt.Button();
        btnCetak = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfNamaOrtu = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data Mahasiswa");

        jLabel2.setText("NIM");

        jLabel3.setText("Nama");

        jLabel4.setText("Alamat ");

        jLabel5.setText("Asal SMA");

        tfNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNIMActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Alamat", "Asal SMA", "Nama Orang Tua"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnUpdate.setActionCommand("Update");
        btnUpdate.setLabel("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnTambah.setLabel("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnDelete.setLabel("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel6.setText("Nama Orang Tua");

        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNIM, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(tfNama, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(tfAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(tfAsal, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(tfNamaOrtu)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnClear)))))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNIM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfNamaOrtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCetak)
                        .addComponent(jButton1)
                        .addComponent(btnClear)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNIMActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (tfNIM.getText().equals("") || tfNama.getText().equals("") || tfAlamat.getText().equals("") || tfAsal.getText().equals("") || tfNamaOrtu.getText().equals("")) {
    JOptionPane.showMessageDialog(null, "Isi semua data");
} else {
    String nim, nama, alamat, asal, ortu;
    nim = tfNIM.getText();
    nama = tfNama.getText();
    alamat = tfAlamat.getText();
    asal = tfAsal.getText();
    ortu = tfNamaOrtu.getText();

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("MataKuliah3PU");
    EntityManager em = emf.createEntityManager();
    em.getTransaction().begin();

    // Mencari data Mahasiswa berdasarkan NIM
    Mahasiswa mahasiswa = em.find(Mahasiswa.class, nim);
    if (mahasiswa == null) {
        JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
    } else {
        // Memperbarui data mahasiswa
        mahasiswa.setNama(nama);
        mahasiswa.setAlamat(alamat);
        mahasiswa.setAsalSma(asal);
        mahasiswa.setNamaOrtu(ortu);
        
        em.getTransaction().commit();
        tampil(); // Memperbarui data pada tampilan
        JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
        
        em.close();
        emf.close();
        tfNIM.setEditable(true);
    }
}

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            tfNIM.setEditable(true);
            if (tfNIM.getText().isEmpty() || tfNama.getText().isEmpty() || tfAlamat.getText().isEmpty() || tfAsal.getText().isEmpty() || tfNamaOrtu.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Isi semua data!", "Input Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            EntityManager entityManager = Persistence.createEntityManagerFactory("MataKuliah3PU").createEntityManager();
            entityManager.getTransaction().begin();

            // Membuat instance Mahasiswa
            Mahasiswa mahasiswa = new Mahasiswa();
            mahasiswa.setNIM(tfNIM.getText());
            mahasiswa.setNama(tfNama.getText());
            mahasiswa.setAlamat(tfAlamat.getText());
            mahasiswa.setAsalSma(tfAsal.getText());
            mahasiswa.setNamaOrtu(tfNamaOrtu.getText());

            // Menyimpan data mahasiswa ke database
            entityManager.persist(mahasiswa);
            entityManager.getTransaction().commit();

            // Memperbarui tampilan data
            tampil();
            JOptionPane.showMessageDialog(null, "Data Mahasiswa berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         String nim = tfNIM.getText();
if (nim.isEmpty()) {
    JOptionPane.showMessageDialog(null, "NIM diisi dulu yaa!", "Input Error", JOptionPane.WARNING_MESSAGE);
    return;
}
int confirm = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data dengan NIM: " + nim + "?",
        "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
if (confirm == JOptionPane.YES_OPTION) {
    EntityManager entityManager = Persistence.createEntityManagerFactory("MataKuliah3PU").createEntityManager();
    try {
        entityManager.getTransaction().begin();
        Mahasiswa mahasiswa = entityManager.find(Mahasiswa.class, nim);
        if (mahasiswa != null) {
            entityManager.remove(mahasiswa);
            entityManager.getTransaction().commit();
            tampil(); // Memperbarui tampilan data setelah penghapusan
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "NIM tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            entityManager.getTransaction().rollback();
        }
    } catch (Exception e) {
        if (entityManager.getTransaction().isActive()) {
            entityManager.getTransaction().rollback();
        }
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } finally {
        entityManager.close();
    }
}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
    try {
         String reportPath = "src/MataKuliah3/DataMahasiswa.jasper";
         HashMap<String, Object> parameters = new HashMap<>();
         JasperPrint print = JasperFillManager.fillReport( reportPath, parameters, conn);
         JasperViewer viewer = new JasperViewer(print, false);
         viewer.setVisible(true);
     }catch (Exception e){
         JOptionPane.showMessageDialog(null, e.getMessage());
     }     
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void tblMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMahasiswaMouseClicked
        int row = jTable1.getSelectedRow();

        String nim = jTable1.getValueAt(row, 0).toString();
        String nama = jTable1.getValueAt(row, 1).toString();
        String alamat = jTable1.getValueAt(row, 2).toString();
        String asal = jTable1.getValueAt(row, 3).toString();
        String ortu = jTable1.getValueAt(row, 4).toString();

        tfNIM.setText(nim);
        tfNama.setText(nama);
        tfAlamat.setText(alamat);
        tfAsal.setText(asal);
        tfNamaOrtu.setText(ortu);
        tfNIM.setEditable(false);
    }//GEN-LAST:event_tblMahasiswaMouseClicked

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {                                          
    JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
int returnValue = jfc.showOpenDialog(null);
EntityManagerFactory emf = Persistence.createEntityManagerFactory("MataKuliah3PU");
EntityManager em = emf.createEntityManager();

if (returnValue == JFileChooser.APPROVE_OPTION) {
    File filePilihan = jfc.getSelectedFile();
    System.out.println("File yang dipilih: " + filePilihan.getAbsolutePath());

    try (BufferedReader br = new BufferedReader(new FileReader(filePilihan))) {
        String baris;
        String pemisah = ";";

        while ((baris = br.readLine()) != null) {
            String[] data = baris.split(pemisah);
            if (data.length == 5) {
                String nim = data[0].trim();
                String nama = data[1].trim();
                String alamat = data[2].trim();
                String asal = data[3].trim();
                String ortu = data[4].trim();

                if (!nim.isEmpty() && !nama.isEmpty() && !alamat.isEmpty() && !asal.isEmpty() && !ortu.isEmpty()) {
                    em.getTransaction().begin();

                    Mahasiswa mahasiswa = new Mahasiswa();
                    mahasiswa.setNIM(nim);
                    mahasiswa.setNama(nama);
                    mahasiswa.setAlamat(alamat);
                    mahasiswa.setAsalSma(asal);
                    mahasiswa.setNamaOrtu(ortu);

                    em.persist(mahasiswa);

                    em.getTransaction().commit();
                    JOptionPane.showMessageDialog(null, "Data Mahasiswa dengan NIM " + nim + " berhasil diinput.");
                    tampil(); // Update tampilan tabel jika ada
                } else {
                    JOptionPane.showMessageDialog(null, "Data tidak lengkap pada NIM " + nim);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Format data tidak valid pada baris: " + baris);
            }
        }
    } catch (FileNotFoundException ex) {
        Logger.getLogger(Mahasiswa.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "File tidak ditemukan.");
    } catch (IOException ex) {
        Logger.getLogger(Mahasiswa.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat membaca file.");
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Format data tidak valid.");
    } finally {
        if (em.isOpen()) {
            em.close(); 
        }
        if (emf.isOpen()) {
            emf.close(); 
        }
    }
}
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
int returnValue = jfc.showOpenDialog(null);
EntityManagerFactory emf = Persistence.createEntityManagerFactory("MataKuliah3PU");
EntityManager em = emf.createEntityManager();

if (returnValue == JFileChooser.APPROVE_OPTION) {
    File filePilihan = jfc.getSelectedFile();
    System.out.println("File yang dipilih: " + filePilihan.getAbsolutePath());

    try (BufferedReader br = new BufferedReader(new FileReader(filePilihan))) {
        String baris;
        String pemisah = ";";

        while ((baris = br.readLine()) != null) {
            String[] data = baris.split(pemisah);
            if (data.length == 5) {
                String nim = data[0].trim();
                String nama = data[1].trim();
                String alamat = data[2].trim();
                String asal = data[3].trim();
                String ortu = data[4].trim();

                if (!nim.isEmpty() && !nama.isEmpty() && !alamat.isEmpty() && !asal.isEmpty() && !ortu.isEmpty()) {
                    em.getTransaction().begin();

                    Mahasiswa mahasiswa = new Mahasiswa();
                    mahasiswa.setNIM(nim);
                    mahasiswa.setNama(nama);
                    mahasiswa.setAlamat(alamat);
                    mahasiswa.setAsalSma(asal);
                    mahasiswa.setNamaOrtu(ortu);

                    em.persist(mahasiswa);

                    em.getTransaction().commit();
                    JOptionPane.showMessageDialog(null, "Data Mahasiswa dengan NIM " + nim + " berhasil diinput.");
                    tampil(); // Update tampilan tabel jika ada
                } else {
                    JOptionPane.showMessageDialog(null, "Data tidak lengkap pada NIM " + nim);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Format data tidak valid pada baris: " + baris);
            }
        }
    } catch (FileNotFoundException ex) {
        Logger.getLogger(Mahasiswa.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "File tidak ditemukan.");
    } catch (IOException ex) {
        Logger.getLogger(Mahasiswa.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat membaca file.");
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Format data tidak valid.");
    } finally {
        if (em.isOpen()) {
            em.close(); 
        }
        if (emf.isOpen()) {
            emf.close(); 
        }
    }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        String nim = jTable1.getValueAt(row, 0).toString();
        String alamat = jTable1.getValueAt(row, 1).toString();
        String nama = jTable1.getValueAt(row, 2).toString();
        String asalSma = jTable1.getValueAt(row, 3).toString();
        String namaOrtu = jTable1.getValueAt(row, 4).toString();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
        tfNIM.setEditable(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Apakah Anda yakin ingin log out?",
        "Konfirmasi Log Out",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        // Tutup form saat ini
        this.dispose();

        // Buka kembali form Login
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setVisible(true);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NadifJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NadifJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NadifJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NadifJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NadifJframe().setVisible(true);
            }
        });
    }

    public void showTable() {
        // Membuat EntityManager untuk mengambil data dari database
        EntityManager entityManager = Persistence.createEntityManagerFactory("MataKuliah3PU").createEntityManager();

        // Query untuk mengambil semua data mahasiswa
        List<Mahasiswa> mahasiswaList = entityManager.createQuery("SELECT m FROM Mahasiswa m", Mahasiswa.class).getResultList();

        // Menampilkan data ke dalam JTable
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Menghapus baris lama dari tabel
        for (Mahasiswa mahasiswa : mahasiswaList) {
            model.addRow(new Object[]{
                mahasiswa.getNIM(),
                mahasiswa.getNama(),
                mahasiswa.getAlamat(),
                mahasiswa.getAsalSma(),
                mahasiswa.getNamaOrtu()
            });
        }
    }

    public void bersih() {
        tfNIM.setText("");
        tfAlamat.setText("");
        tfNama.setText("");
        tfAsal.setText("");
        tfNIM.setEditable(true);
    }

    DefaultTableModel tbmk;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnClear;
    private java.awt.Button btnDelete;
    private java.awt.Button btnTambah;
    private java.awt.Button btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfAsal;
    private javax.swing.JTextField tfNIM;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNamaOrtu;
    // End of variables declaration//GEN-END:variables

}